import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import axe from 'axe-core';
const port=4305,base=`http://127.0.0.1:${port}`,output=new URL('../test-output/design/',import.meta.url);
const proc=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),A11YLENS_TEST_HEADLESS:'1'},stdio:'pipe'});let browser;
try{
 for(let i=0;i<60;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 await mkdir(output,{recursive:true});browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);for(const path of ['/brand/a11ylens-mark.svg','/assets/fonts/geist-latin.woff2','/lens-tokens.css','/theme.js'])assert.equal((await page.request.get(base+path)).status(),200);
 assert.equal(await page.locator('h1').innerText(),'Accessibility Insights.\nClear Priorities.\nActionable Fixes.');
 const report=JSON.parse(await readFile(new URL('../test-output/report.json',import.meta.url),'utf8'));
 async function auditUI(label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' overflow');await page.evaluate(axe.source);const r=await page.evaluate(()=>axe.run());assert.deepEqual(r.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)})),[],label);}
 for(const theme of ['light','dark'])for(const [width,height]of [[1440,1050],[375,812],[844,390]]){
  await page.setViewportSize({width,height});await page.locator('#theme-select').selectOption(theme);await page.getByRole('button',{name:'Home',exact:true}).click();await auditUI(`home ${theme} ${width}`);await page.screenshot({path:new URL(`home-${theme}-${width}.png`,output).pathname,fullPage:true});
  await page.evaluate(a=>localStorage.setItem('a11ylens-audits-v1',JSON.stringify([a])),report);await page.reload();await page.getByRole('button',{name:'Audit overview',exact:true}).click();await auditUI(`queue ${theme} ${width}`);await page.screenshot({path:new URL(`queue-${theme}-${width}.png`,output).pathname,fullPage:true});
  await page.locator('[data-detail]').first().click();await auditUI(`evidence ${theme} ${width}`);await page.screenshot({path:new URL(`evidence-${theme}-${width}.png`,output).pathname,fullPage:true});await page.keyboard.press('Escape');assert.ok(await page.locator('[data-detail]').first().evaluate(e=>e===document.activeElement));
 }
 await page.setViewportSize({width:1440,height:1050});await page.locator('#theme-select').selectOption('system');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');const other=await context.newPage();await other.goto(base);await other.locator('#theme-select').selectOption('dark');await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('#theme-select').inputValue(),'dark');await other.close();await page.reload();assert.equal(await page.locator('#theme-select').inputValue(),'dark');
 await page.locator('#home-url').fill('https://example.com/selected');await page.getByRole('button',{name:'Start audit',exact:true}).click();assert.equal(await page.locator('#site-url').inputValue(),'https://example.com/selected');await page.keyboard.press('Escape');await page.getByRole('button',{name:'New audit',exact:true}).first().click();assert.equal(await page.locator('#site-url').inputValue(),'');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Audit overview',exact:true}).click();await page.locator('[data-rule]').first().click();assert.notEqual(await page.locator('#type-filter').inputValue(),'');await page.locator('#finding-search').fill('no-such-rule-or-page');assert.equal(await page.locator('tbody tr').count(),0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.ok(await page.locator('tbody tr').count());await page.getByRole('tab',{name:'All checks'}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:'Page coverage'}).getAttribute('aria-selected'),'true');
 await page.getByRole('button',{name:'Home',exact:true}).click();assert.equal(await page.locator('[data-history]').count(),1);await page.locator('[data-history]').first().click();assert.ok(await page.locator('.site-info').isVisible());
 await page.setViewportSize({width:375,height:812});await page.addStyleTag({content:'html{font-size:28px} button,input,select,textarea,p{font-size:1rem!important}'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'200% text overflow');await page.screenshot({path:new URL('text-200.png',output).pathname,fullPage:true});assert.deepEqual(errors,[]);
 console.log('Design passed: both themes and three viewport sizes, axe, overflow, evidence focus restoration, OS/cross-tab themes, fresh setup and URL handoff, filters, keyboard tabs, recents, 200% text and local assets.');
}finally{await browser?.close();proc.kill('SIGTERM');}
