process.env.A11YLENS_TEST_HEADLESS='1';
import {chromium} from 'playwright';
import {scan,createSession,confirmSession,closeSession,sessions} from '../src/scanner.js';
import http from 'node:http';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const out=[];const record=(scenario,expected,observed,passed)=>{out.push({scenario,expected,observed,passed});console.log(JSON.stringify(out.at(-1)))};
const wrap=body=>`<!doctype html><html lang="en"><title>Scenario fixture</title><main><h1>Account</h1>${body}</main></html>`;
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');if(req.url==='/redirect'){res.writeHead(302,{Location:'/destination'});return res.end()};if(req.url==='/session'){return res.end(wrap(`<a href="/logout">Sign out</a><script>sessionStorage.setItem('token','fixture-session')</script>`))};if(req.url==='/protected'){return res.end(wrap(`<div id="content"></div><script>document.querySelector('#content').innerHTML=sessionStorage.getItem('token')?'<button id="private-failure"></button>':'<p>Please sign in to see protected content</p>'</script>`))};if(req.url==='/password-settings')return res.end(wrap('<label>New password<input type="password" autocomplete="new-password"></label><button id="broken"></button>'));res.end(wrap('<details><summary>More options</summary><button id="hidden-failure"></button></details>'))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const makeJob=()=>({signal:new AbortController().signal,gaps:[],progress:{}});
const appPort=4303,base=`http://127.0.0.1:${appPort}`;
const app=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(appPort)},stdio:'pipe'});
let browser;
try{
 for(let i=0;i<60;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 const redirect=await scan({url:url+'/redirect',pages:[url+'/redirect']},makeJob());record('Redirect followed by disclosure','Expanded button is audited after same-origin redirect',{found:redirect.assets.some(a=>a.selector.includes('hidden-failure')),gaps:redirect.coverage.gaps},redirect.assets.some(a=>a.selector.includes('hidden-failure')));
 const password=await scan({url:url+'/password-settings',pages:[url+'/password-settings']},makeJob());record('Password settings page','Password change field does not mark whole page unverified',{states:password.pageResults.map(p=>p.status),gaps:password.coverage.gaps},password.assets.some(a=>a.rule==='button-name'));
 const auth=await createSession(url+'/session');try{await confirmSession(auth.id);const result=await scan({url:url+'/session',pages:[url+'/protected'],sessionId:auth.id},makeJob());record('Session-storage authentication','Confirmed browser authentication survives scanning',{found:result.assets.some(a=>a.selector.includes('private-failure')),states:result.pageResults.map(p=>p.status),gaps:result.coverage.gaps},result.assets.some(a=>a.selector.includes('private-failure')))}finally{await closeSession(auth.id)}
 browser=await chromium.launch();const page=await browser.newPage();await page.goto(base);
 await page.getByRole('button',{name:'New audit',exact:true}).first().click();await page.locator('#site-url').fill(url);await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await page.locator('#next').click();await page.locator('#next').click();const pending=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('a11ylens-active-job')));await page.reload();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});const history=await page.evaluate(()=>JSON.parse(localStorage.getItem('a11ylens-audits-v1')));record('Refresh while scanning','One completed saved report after refresh',{records:history.length,activeJob:await page.evaluate(()=>sessionStorage.getItem('a11ylens-active-job')),requestId:pending.input.requestId},history.length===1);
 await page.getByRole('button',{name:'New audit',exact:true}).last().click();await page.locator('#site-url').fill(url);await page.getByRole('radio',{name:'Requires sign-in'}).check();let sid;await page.route('**/api/sessions',async route=>{const response=await route.fetch();sid=(await response.json()).id;await route.fulfill({response})});await page.locator('#sign-in').click();await page.waitForFunction(()=>document.querySelector('#sign-in')?.textContent.includes('Confirm'));await page.request.delete(base+'/api/sessions/'+sid,{headers:{'X-A11YLens':'1'}});await page.locator('#sign-in').click();await page.waitForFunction(()=>document.querySelector('#url-error')?.textContent);record('Closed sign-in browser retry','Offer a fresh sign-in browser after session closes',{error:await page.locator('#url-error').innerText(),button:await page.locator('#sign-in').innerText()},(await page.locator('#sign-in').innerText()).includes('Open sign-in'));await page.locator('#sign-in').click();await page.waitForFunction(()=>document.querySelector('#sign-in')?.textContent.includes('Confirm'));await page.getByRole('button',{name:'Close dialog'}).click();
 await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='a11ylens-audits-v1')throw new DOMException('Quota exceeded','QuotaExceededError');return original.call(this,k,v)}});await page.getByRole('button',{name:'New audit',exact:true}).last().click();await page.locator('#site-url').fill(url);await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await page.locator('#next').click();await page.locator('#next').click();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});record('Storage full on completion','Show persistent unsaved report warning and allow export',{warning:await page.locator('[role=alert]').innerText(),exportVisible:await page.getByRole('button',{name:'Export report'}).isVisible()},(await page.locator('[role=alert]').innerText()).includes('Report not saved'));
 assert.equal(out.length,6);assert.deepEqual(out.filter(x=>!x.passed),[],'All scenario regressions must pass');
}finally{await browser?.close();app.kill('SIGTERM');server.closeAllConnections();await new Promise(r=>server.close(r));await writeFile(new URL('./scenarios.json',import.meta.url),JSON.stringify(out,null,2));}
