import { chromium } from 'playwright';
import { randomUUID } from 'node:crypto';
import { checkLogin } from './authentication.js';

export const LIMITS={pages:200,queue:3000,scrolls:24,interactions:16,states:18,timeout:20000,resourceTimeout:7000};
export const sessions=new Map();
const unsafe=/\b(?:add[-_ ]?to[-_ ]?cart|remove|delete|destroy|reset|submit|save|send|buy|purchase|pay|checkout|subscribe|unsubscribe|upload|download|log[-_ ]?out|sign[-_ ]?out)\b/i;
export function validURL(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Use an HTTP or HTTPS URL without embedded credentials.');u.hash=/^#(?:\/|!)/.test(u.hash)?u.hash:'';return u.href}
function actionURL(raw){try{const u=new URL(raw);return unsafe.test(u.pathname)||['action','do','cmd','operation'].some(k=>unsafe.test(u.searchParams.get(k)||''))}catch{return true}}
function cancelled(signal){if(signal?.aborted)throw Error('Audit cancelled.');}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function gap(job,page,reason,detail=''){const key=page+'|'+reason+'|'+detail;if(!job.gaps.some(x=>x.key===key))job.gaps.push({key,page,reason,detail});}
async function guard(context,job){await context.unroute('**/*');await context.route('**/*',async route=>{const req=route.request();if(!['GET','HEAD','OPTIONS'].includes(req.method())||actionURL(req.url())){gap(job,new URL(req.url()).origin+new URL(req.url()).pathname,'Blocked action request',req.method());await route.abort().catch(()=>{});}else await route.continue().catch(()=>{});});}
export async function createSession(url){url=validURL(url);const browser=await chromium.launch({headless:process.env.A11YLENS_TEST_HEADLESS==='1'});try{const context=await browser.newContext({viewport:{width:1366,height:900}});const page=await context.newPage();await page.goto(url,{waitUntil:'domcontentloaded',timeout:LIMITS.timeout}).catch(e=>{if(!e.message.includes('Timeout'))throw e;});const id=randomUUID();const session={id,browser,context,page,url,confirmed:false,busy:false,lastUsed:Date.now()};sessions.set(id,session);browser.on('disconnected',()=>sessions.delete(id));return{id,url:page.url()}}catch(e){await browser.close();throw e}}
export async function confirmSession(id){const s=sessions.get(id);if(!s||s.page.isClosed())throw Error('The sign-in window was closed or expired. Open a new session.');const result=await checkLogin(s.page,{loginUrl:s.url},new URL(s.url).origin);if(!result.accepted)throw Error(result.message);s.confirmed=true;s.lastUsed=Date.now();return{confirmed:true,url:s.page.url()}}
export async function closeSession(id){const s=sessions.get(id);sessions.delete(id);await s?.browser.close().catch(()=>{});}
setInterval(()=>{for(const [id,s] of sessions)if(!s.busy&&Date.now()-s.lastUsed>30*60*1000)closeSession(id)},60000).unref();

async function acquire(input,job){let s;if(input.sessionId){s=sessions.get(input.sessionId);if(!s?.confirmed)throw Error('Your sign-in session has expired. Sign in again.');if(s.busy)throw Error('This browser session is already running an audit.');if(new URL(input.url).origin!==new URL(s.url).origin)throw Error('The signed-in session belongs to a different website.');s.busy=true;s.lastUsed=Date.now();}else{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1366,height:900}});s={browser,context,page:await context.newPage(),private:false};}job.browser=s.browser;await guard(s.context,job);return s;}
async function release(s,input){if(!s)return;if(input.sessionId){s.busy=false;s.lastUsed=Date.now();}else await s.browser.close().catch(()=>{});}
async function navigate(page,url,force=false){if(force||page.url()!==url){const response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:LIMITS.timeout});page._a11yLensResponse={url,status:response?.status()||0};}if(page._a11yLensResponse?.url===url&&page._a11yLensResponse.status>=400)throw Error('Page returned HTTP '+page._a11yLensResponse.status);await page.waitForLoadState('networkidle',{timeout:1800}).catch(()=>{});}
async function links(page,origin){return page.evaluate(origin=>[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(h=>{try{return new URL(h).origin===origin}catch{return false}}),origin)}
async function scrollPage(page,job,url){let exhausted=false;for(let i=0;i<LIMITS.scrolls;i++){cancelled(job.signal);const atEnd=await page.evaluate(()=>{window.scrollBy(0,Math.max(400,innerHeight*.8));return scrollY+innerHeight>=document.documentElement.scrollHeight-3});await delay(130);if(atEnd){const still=await page.evaluate(()=>scrollY+innerHeight>=document.documentElement.scrollHeight-3);if(still){exhausted=true;break;}}}if(!exhausted)gap(job,url,'Scroll limit reached','Lazy or infinite content may remain undiscovered.');await page.evaluate(()=>scrollTo(0,0));}
export async function discover(input,job){let s;try{s=await acquire(input,job);const origin=new URL(input.url).origin,queue=[input.url],seen=new Set(),pages=[];while(queue.length&&seen.size<LIMITS.pages){cancelled(job.signal);const url=queue.shift();if(seen.has(url))continue;seen.add(url);job.progress={message:`Discovering pages: ${seen.size}`,done:seen.size,total:seen.size+queue.length};try{await navigate(s.page,url);if(new URL(s.page.url()).origin!==origin){gap(job,url,'Redirected outside website');continue;}await scrollPage(s.page,job,url);pages.push({url,path:new URL(url).pathname+new URL(url).search+new URL(url).hash,title:await s.page.title()});for(const raw of await links(s.page,origin)){let h;try{h=validURL(raw)}catch{continue}if(!seen.has(h)&&!queue.includes(h)&&!actionURL(h)){if(queue.length<LIMITS.queue)queue.push(h);else gap(job,input.url,'Discovery queue limit reached');}}}catch(e){cancelled(job.signal);gap(job,url,'Page could not be discovered',e.message.split('\n')[0]);}}if(queue.length)gap(job,input.url,'Page discovery limit reached',`${queue.length} queued pages remain; limit ${LIMITS.pages}.`);return{pages,gaps:job.gaps,complete:false,limits:LIMITS};}finally{await release(s,input)}}


export { acquire, release, navigate, scrollPage, cancelled, gap, unsafe };
